Ms 1.3 updates michael
BitcoinDesign/Bitcoin-Core-App pull request #76
Opened 2023-10-23 17:34 UTC by rabbitholiness

2023-11-22 09:44 UTC, GBKS commented
Can you please remove all files and file changes that are unrelated to the content you're editing? That includes:
- .DS_Store
- Gemfile.lock
- LICENSE
- README.md
- assets/images/import-wallet/.DS_Store
- images/bitcoin-core-app-versions.png
- images/cross-platform-layouts.png

2023-11-22 10:03 UTC, GBKS requested changes
Thanks for adding this. I'd like to request a whole bunch of changes. Many are just related to exporting and embedding images correctly, should be a piece of cake to take care of. There are also some text suggestions, and I left a separate comment about removing the files unrelated to your changes.

Could you please also use the same image background and spacing as the other pages? I always set them up with 50px padding, 50px gap between screens and #E5E5E5 as background color (here in [Figma](https://www.figma.com/file/ek8w3n3upbluw5UL2lGhRx/Bitcoin-Core-App-Design?type=design&node-id=7962%3A46301&mode=design&t=SyPxAlatweA5cHDu-1)). That will give us some nice consistency that allows readers to focus on the content itself.

2023-11-22 10:03 UTC, GBKS commented on pages/milestones/1-3-import.md
> -	image = "/assets/images/import-wallet/flow.png"
If you remove a reference to an image and the image is not used anymore, please remove the image file itself from the repo as well.

2023-11-22 10:03 UTC, GBKS commented on pages/milestones/1-3-import.md
> +	big = "/assets/images/import-wallet/import_flow.png"
Big size cannot be the same as the regular size. It should be high-res enough that someone can dig in and see all the details. For flows, that can end up being quite big.

2023-11-22 10:03 UTC, GBKS commented on pages/milestones/1-3-import.md
>  	retina = "/assets/images/import-wallet/flow@2x.png"
Make sure to also replace the retina image.

2023-11-22 10:03 UTC, GBKS commented on pages/milestones/1-3-import.md
> +	image = "/assets/images/import-wallet/import_flow.png"
Regular image should be 800px wide. Retina twice that.

2023-11-22 10:03 UTC, GBKS commented on pages/milestones/1-3-import.md
>  	height = 368
Make sure to update the height once you changed the images to the right dimensions.

2023-11-22 10:03 UTC, GBKS commented on pages/milestones/1-3-import.md
> +	retina = "/assets/images/import-wallet/entry-points@2x.png"
big image missing

2023-11-22 10:03 UTC, GBKS commented on pages/milestones/1-3-import.md
> +	height = 368
Make sure to update the height.

2023-11-22 10:03 UTC, GBKS commented on pages/milestones/1-3-import.md
> +The full details are available in the settings section for full review. Note that the information displayed this screen will vary based on the specific use case. For intance, if a user imports from a
```suggestion
The full details are available in the settings section for full review. The information displayed on this screen will vary based on the specific use case. For instance, if a user imports from an XPUB, the application will not know the wallet name.
```

2023-11-22 10:03 UTC, GBKS commented on pages/milestones/1-3-import.md
> +- Etc.
```suggestion
```

2023-11-22 10:03 UTC, GBKS commented on pages/milestones/1-3-import.md
> +	height = 184
big image missing and image size needs updated

2023-11-22 10:03 UTC, GBKS commented on pages/milestones/1-3-import.md
> +3. What does the user need to do (remedy).
```suggestion
3. What the user can do (remedy).
```

2023-11-22 10:03 UTC, GBKS commented on pages/milestones/1-3-import.md
> +- Directly after the onboarding flow, if the user is doing a fresh install of the application.
```suggestion
- Directly at the end of the onboarding flow, if the user is doing a fresh install of the application.
```

2023-11-22 10:03 UTC, GBKS commented on pages/milestones/1-3-import.md
> +- Through the wallet selector dropdown, if he already has a different wallet.
```suggestion
- Through the wallet selector dropdown, if a wallet was already previously added. 
```

2023-11-22 10:03 UTC, GBKS commented on pages/milestones/1-3-import.md
> +- From the settings screen, if the application has been previously used in node only mode.
Didn't we just have a small add wallet button in the top-left corner?

2023-11-22 10:03 UTC, GBKS commented on pages/milestones/1-3-import.md
> +	alt-text = "Mockup showing the import screen."
big image missing and wrong image height.

2023-11-22 10:03 UTC, GBKS commented on pages/milestones/1-3-import.md
> +Users can import a wallet by choosing a wallet file from their file system. In that case, the native file picker from their operating system. On desktop they can also just drag and drop the file into
```suggestion
Users can import a wallet by choosing a wallet file from their file system (via the native operating system file picker). On desktop, they can also drag and drop the file into the application window. 
```

2023-11-22 10:03 UTC, GBKS commented on pages/milestones/1-3-import.md
> +Users have two main options to import a wallet: by loading a wallet file into the application or by copy-pasting an extended public key, bitcoin address or descriptor.
```suggestion
Users have two main options to import a wallet: by loading a wallet file into the application or by entering an extended public key, bitcoin address or descriptor.
```

2023-11-22 10:03 UTC, GBKS commented on pages/milestones/1-3-import.md
> +#### Paste XPUB, bitcoin address or wallet descriptor
```suggestion
#### Copy & paste
```

2023-11-22 10:03 UTC, GBKS commented on pages/milestones/1-3-import.md
> +Users can also copy and paste an XPUB, bitocin address or wallet descriptor to import their wallet.
```suggestion
Users can also copy and paste an extended public key (XPUB), bitcoin address or wallet descriptor to import their wallet.
```

2023-11-22 10:03 UTC, GBKS commented on pages/milestones/1-3-import.md
> +- Potentially more
```suggestion
- Potentially more  based on wallet type
```

2023-11-22 10:03 UTC, GBKS commented on pages/milestones/1-3-import.md
> +{% include picture.html
big image missing and image height incorrect.

2023-12-01 10:40 UTC, rabbitholiness commented
@GBKS I think I addressed all of the issues you mentioned.

2023-12-07 12:32 UTC, GBKS requested changes
Thanks for fixing (almost) everything. Could you please remove the Gemfile and the 3 .DS_Store files from the PR? The .DS_Store files are likely hidden, so may need to enable showing hidden files in finder. Otherwise it's ready to go, IMHO.

2023-12-07 12:40 UTC, promag commented
Add .gitignore to avoid committing `.DS_Store` and other unwanted files, see https://stackoverflow.com/a/107921.

2023-12-07 12:44 UTC, GBKS commented
@promag good idea. I just did that on the `gh-pages` branch (we had a `.gitignore` already, I added a `.DS_Store` entry.

2024-01-12 08:58 UTC, rabbitholiness commented
> Thanks for fixing (almost) everything. Could you please remove the Gemfile and the 3 .DS_Store files from the PR? The .DS_Store files are likely hidden, so may need to enable showing hidden files in finder. Otherwise it's ready to go, IMHO.

@GBKS I removed the Gemfile and the .gitignore (as suggested by promag), but I couldn't find any .DS_Store file, even after showing hidden files.

2024-01-12 10:11 UTC, GBKS commented
ACK. Ready to go. I did 3 clean-up commits to:

- Restore the gitignore and Gemfile files (we do need them, just the version that is already in the repo, not the changes in this PR).
- Delete the _site directory. It contains the files your computer creates when running the site locally. We don't want them in the repo.
- Deleted .DS_Store files, which MacOS uses to store information about folders.

Much tidier now.

2024-01-12 10:11 UTC, merged