Research page
BitcoinDesign/Bitcoin-Core-App pull request #94
Opened 2024-01-22 13:02 UTC by mouxdesign

The initial PR is to create a research page within the Bitcoin Core App website to document the research done as well as link out to them.

2024-01-22 14:23 UTC, GBKS requested changes
Great job getting this in. I did a read through and found a few small things.

2024-01-22 14:23 UTC, GBKS commented on pages/research.md
> +By integrating user experience research into the development process in Bitcoin Core App we have gained insights into user behaviours, needs, and challenges as well as an overview of the competitive
```suggestion
By integrating user experience research into the development process in Bitcoin Core App we have gained some insights into user behaviours, needs, and challenges as well as an overview of the competitive environment.
```
Making it sound less absolute since I don't think we understand every user and use case (and maybe never will).

2024-01-22 14:23 UTC, GBKS commented on pages/research.md
> +Research in the Bitcoin Core App project takes varied forms, initiated by a central question guiding the projects focus. The Bitcoin UX Research toolkit adheres to a question-first approach, helping
```suggestion
Research in the Bitcoin Core App project takes varied forms, initiated by a central question guiding the projects focus. The [Bitcoin UX Research toolkit](https://bitcoinresearch.xyz/) adheres to a question-first approach, helping us tailor methodologies to the specific questions at hand.
```
Adding a link, since the reader may not be familiar with the tool kit. You could also add a note about how the research is tryin to follow what's laid out in the the tool kit.

2024-01-22 14:23 UTC, GBKS commented on pages/research.md
> +## Bitcoin Core App User Research efforts
```suggestion
## Completed research efforts
```

2024-01-22 14:23 UTC, GBKS commented on pages/research.md
> +To date there have been various research efforts that have been done on Bitcoin Core App and the research sprints that have been done have had various roles within the project.
```suggestion
There have been various research efforts around this project and the Bitcoin Core QT GUI, and the research sprints that have been done have had various roles within the project.
```
Let's be specific here again with the different projects. We focus on UIs, not on the node daemon, network consensus, CLI, and all the others stuff in Bitcoin Core. Previous research was done the QT GUI. The Bitcoin Core App is not really live and used, so we have not really done research on that yet. We can only research to guide our design and development forwards.

2024-01-22 14:23 UTC, GBKS commented on pages/research.md
> +Privacy is a cornerstone in Bitcoin user research, affecting two critical areas:
```suggestion
Privacy is a cornerstone in bitcoin user research, affecting two critical areas:
```

2024-01-22 14:23 UTC, GBKS commented on pages/research.md
> +The research done on this project so far has been organized and initiated within the Bitcoin Design Community. An additional research initiative on nodes has been done by a bitcoin Core developer as
```suggestion
The research done on this project so far has been organized and initiated within the [Bitcoin Design Community](http://bitcoin.design). An additional research initiative on nodes has been done by a Bitcoin Core developer as well.  Within the Bitcoin Design Community there have been calls organized so that people can contribute, as well as understand the research efforts.
```

2024-01-22 14:23 UTC, GBKS commented on pages/research.md
> +** add in image
```suggestion
```
Remove if there is no image.

2024-01-22 14:23 UTC, GBKS commented on pages/research.md
> +The most popular direct and indirect competing UI’s were [identified.](https://docs.google.com/spreadsheets/d/1igEgshDrDrf5g_ZBbmeA44pwxtT2t059xJwW82ItD2A/edit#gid=0)
```suggestion
The most popular direct and indirect competing UI’s were [identified](https://docs.google.com/spreadsheets/d/1igEgshDrDrf5g_ZBbmeA44pwxtT2t059xJwW82ItD2A/edit#gid=0).
```

2024-01-22 14:23 UTC, GBKS commented on pages/research.md
> +[User stories](https://www.interaction-design.org/literature/topics/user-stories) are specific use cases describing when and how a person might use an application. Think of a user story as a singular
```suggestion
[User stories](https://www.interaction-design.org/literature/topics/user-stories) are specific use cases describing when and how a person might use an application. Think of a user story as a singular task which a user would aim to achieve when opening the application. User stories are usually first created by stakeholders and then verified by conducting research and speaking with users.
```

2024-01-22 14:23 UTC, GBKS commented on pages/research.md
> +- [Google doc](https://docs.google.com/document/d/1lLDfk2rqxyE1qq74isdAvrd6gZxpxzY55rkdOIfV6Yc/edit#heading=h.qbzoxhysypzv)
Make sure these links don't have edit rights.

2024-01-22 14:23 UTC, GBKS commented on pages/research.md
> +At the beginning of 2021 a survey was run by Ava Chow, a bitcoin core developer. This survey was sponsored by [MIT's Digital Currency Initiative] (https://dci.mit.edu/) and in partnership with [Maide
```suggestion
At the beginning of 2021 a survey was run by Ava Chow, a Bitcoin Core developer. This survey was sponsored by [MIT's Digital Currency Initiative] (https://dci.mit.edu/) and in partnership with [Maiden Labs](http://maiden.global/).  Its goal was to better understand the people who run nodes and use the Bitcoin Core wallet, as well as people familiar with Bitcoin but who maybe don’t run a node (yet).
```

2024-01-22 14:23 UTC, GBKS commented on pages/research.md
> +This initiative was to understand both current as well as potential users of the Bitcoin Core App. One on one interviews were done to understand the pushes, pulls as well as use cases of people using
```suggestion
This initiative was to understand both current as well as potential users of the Bitcoin Core App. One on one interviews were done to understand the pushes, pulls as well as use cases of people using Bitcoin Core.
```

2024-01-22 14:23 UTC, GBKS commented on pages/research.md
> +- Joining a call: Joining in on the design calls allows contributors to get a feel of the project as well as which areas of the UI are being worked on at the moment. Calls are added to the [Bitcoin D
```suggestion
- Joining a call: This allows contributors to get a feel of the project as well as which areas of the UI are being worked on at the moment. Calls are added to the [Bitcoin Design Community calender](https://bitcoin.design/calendar/).
```

2024-01-29 10:03 UTC, mouxdesign commented on pages/research.md
> +- [Google doc](https://docs.google.com/document/d/1lLDfk2rqxyE1qq74isdAvrd6gZxpxzY55rkdOIfV6Yc/edit#heading=h.qbzoxhysypzv)
```suggestion
- [Google doc](https://docs.google.com/document/d/19eYP5e8qp5SCdNIzPHC49C5LFlnAvgiEjmUi3JTRmtc/edit?usp=sharing
```

2024-01-29 10:03 UTC, mouxdesign commented on pages/research.md
> +- [Google doc](https://docs.google.com/document/d/1lLDfk2rqxyE1qq74isdAvrd6gZxpxzY55rkdOIfV6Yc/edit#heading=h.qbzoxhysypzv)
Copied the google doc and changed edit rights.

2024-01-30 15:13 UTC, mouxdesign commented
Pushed some images as the most recent commit. Its ready for another review. 🙌

2024-01-31 09:34 UTC, GBKS commented
ACK.

2024-01-31 09:34 UTC, merged